# Generated by Django 3.1.2 on 2020-10-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20201017_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='attributes',
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ManyToManyField(blank=True, default='', to='test.Attribute')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.subcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test.subitem'),
        ),
    ]
