# Generated by Django 3.1.2 on 2020-10-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20201017_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryAttribute',
        ),
        migrations.AddField(
            model_name='subitem',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
